### ISSUE TITLE
Swift3

### ISSUE THREAD

**Issue by francoisduchemin** [peterprokop/SwiftOverlays#22]
Hey Peter, thanks for your library.
Do you know how to include the swift 3 branch in carthage?

I tried to put the following string in my cartfile:
github "peterprokop/SwiftOverlays" "swift-3.0"

But when I update I get the following error messages:
SwiftOverlays/SwiftOverlays/SwiftOverlays.swift:303:27: error: value of type 'CGRect' has no member 'offsetInPlace'
SwiftOverlays/SwiftOverlays.swift:310:27: error: value of type 'CGRect' has no member 'offsetInPlace'
SwiftOverlays/SwiftOverlays/SwiftOverlays.swift:415:58: error: cannot call value of non-function type 'UIColor'
SwiftOverlays.swift:418:70: error: cannot call value of non-function type 'UIScreen'
SwiftOverlays/SwiftOverlays.swift:490:42: error: cannot call value of non-function type 'UIApplication'

Thanks,
Francois.

**Comment by illyaBakurov** [comment]
The same is happening with CocoaPods.

**Comment by emonfil87** [comment]
The same is happening with Manually installation.

**Comment by illyaBakurov** [comment]
changing offsetInPlace to offsetBy solved the issue.

**Comment by peterprokop** [comment]
@francoisduchemin @illyaBakurov @emonfil87 Guys, I've updated `swift-3.0` branch, can you please check again? Will update CocoaPods when will have some free time.

**Comment by levibostian** [comment]
@peterprokop I ran the newly updated swift-3.0 branch and it works great from my testing. Simple overlay with text and then removing it.

**Comment by francoisduchemin** [comment]
@peterprokop Same here everything is working fine with the the updated swift-3.0 branch. Thanks!

**Comment by giacgbj** [comment]
@peterprokop What about merging this branch into the head?

**Comment by peterprokop** [comment]
@giacgbj sorry for the delays, was really busy. `swift-3.0` is now merged to `master`

**Comment by giacgbj** [comment]
@peterprokop Great! Waiting for the release to cleanup my Podfile :-)

**Comment by peterprokop** [comment]
@giacgbj Can you please check https://github.com/peterprokop/SwiftOverlays/releases/tag/3.0.0 ?

**Comment by giacgbj** [comment]
@peterprokop I just tested the methods I use in my application and they seem to work properly. In my opinion, you can release it.

**Comment by kevinkowalew** [comment]
I installed the most recent version (2.0.1) using Cocoapods, however, it appears to not be the updated Swift 3 version.  Any ideas why this may be happening?

**Comment by peterprokop** [comment]
@kevinkowalew I still haven't updated the pod specs, will do that this evening (hopefully)

**Comment by kevinkowalew** [comment]
sounds great Peter, thanks!

**Comment by lucletruc** [comment]
@peterprokop agree with kevin, please fix faster :)

**Comment by peterprokop** [comment]
@kevinkowalew @lucletruc Guys, I've pushed new podspec. Can you please check if everything works as expected?

**Comment by lucletruc** [comment]
@peterprokop ran  `pod update` works like a charm 👍 :)

**Comment by kevinkowalew** [comment]
same here, thanks Peter!
